### ISSUE TITLE
Instructions in README not working

### ISSUE THREAD

**Issue by droctothorpe** [kazumatu981/markdown-it-kroki#1]
The demo in this repo works because it's nested in this repo and as a result, the reference to `..index` [here](https://github.com/kazumatu981/markdown-it-kroki/blob/main/demo/marp.config.js#L4) resolves. But when you step through the README, it fails with the following error:

```
❯ marp -s -c marp.config.js

[ ERROR ] Failed converting Markdown. (Cannot find module '../index'
```

What should it say instead of `../index`?

**Comment by droctothorpe** [comment]
Nvm. The following did the trick:
```
    engine: ({ marp }) => marp.use(require('@kazumatu981/markdown-it-kroki'), {
```

**Comment by kazumatu981** [comment]
Sorry I've mitake.... I'll fix my read me file!
