### ISSUE TITLE
Some types of graph not showing

### ISSUE THREAD

**Issue by kirnhans** [kazumatu981/markdown-it-kroki#18]
I've tested the sample XY chart, git graph, mindmap, quadrant graphs, block chart, packet graph and pie chart from [Mermaid](https://mermaid.live/). They don't show up when I compile using marp. The flowchart TD graph, sequence, class, state, ER diagram, user journey and Gantt chart show fine.

Here's my markdown:
```---
marp: true
---

\```mermaid[mermaid image]
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
\```
```
(remove backslashes)

From what I can tell, embed isn't taking the width from its children elements properly for width: max-content to work. 

Setting the width manually like below provides a workaround:
```
embed {
width: 700px;
}```

**Comment by kazumatu981** [comment]
Thank you for your testing, and I'm so sorry this library does not show some types of graph `mermaid`....
My library, as you know, depends on Krokii.io web service, so I can not support your wants by my library......

But I can suggest to better answar for this case. (as you said "manually", but I'll introduce some tricks.)

```markdown
marp:true
---

<style>
embed[title="mermaid image"] {
width: 700px;
}
</style>

\```mermaid[mermaid image]
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
\```

```
*(remove backslashes)*

This method called **Tweek Style** (see [here](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown)) in Marp Official. and my library embed bracketed text into title attribute of `<embed>`.
I think this method work well... how do you think.

**Comment by kirnhans** [comment]
All good, sorry for laying this at your door!

Thanks for the Tweek, I'll be sure to use it whenever I try to use the other types of mermaid graphs!
