### ISSUE TITLE
Not clickable Link Issue when used with vitepress

### ISSUE THREAD

**Issue by ezzle** [kazumatu981/markdown-it-kroki#2]
Hi,

I am trying to use  this plugin with vitepress.

Diagrams are displayed coorectly . **But Links are not clickable.**

I created the following project  to illustrate the issue.

https://stackblitz.com/edit/vite-qdacts?file=docs%2Findex.md

Best regards

**Comment by kazumatu981** [comment]
Hi,

Thank you for your trying.
But, I don't have expected to use **clickable** object.
So I'll try to support this issue.

Maybe, It will work to use krokii's [Diagram Options](https://docs.kroki.io/kroki/setup/diagram-options/).....
Just a moment please.

**Comment by kazumatu981** [comment]
Hi,

I have researched my code, and some documents.
hm... I've use `<img>` tag for embed diagrams, It should be use `<embed>` tag......
I'll support soon......

**Comment by kazumatu981** [comment]
Release as v 1.2.1. on [NPM](https://www.npmjs.com/package/@kazumatu981/markdown-it-kroki)
Please enjoy !

**Comment by ezzle** [comment]
Fine.

Thank you
