### ISSUE TITLE
INLINE [instead of Embedded] svg option : relative link issue

### ISSUE THREAD

**Issue by ezzle** [kazumatu981/markdown-it-kroki#4]
Hi.

**INLINE SVG option**
With embed tag, relative links inside the kroki diagram are resolved relative to the kroki server instead of the embedding document server.

I am using Kroki with Vitepress Static site generator. 

The kroki team suggest "INLINE" SVG at the build time as the solution to  issue
Could you provide an option for inline svg please.

**Issue History on Kroki** 
https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/Relative.20link.3A.20relative.20to.20site.20base.20instead.20of.20kroki.20server

**Sample repository:**
https://stackblitz.com/edit/vite-sepohb?file=docs%2Findex.md

For correct rendering on stackblitz : use the button "Open in New Tab"

Besr regards,

Tshitshi

**Comment by ezzle** [comment]
For correct rendering on stackblitz : use the button "Open in New Tab"

**Comment by kazumatu981** [comment]
Konbanha.

 I'm so sory, but I'll **NOT** implement INLINE SVG option.

I think mordern JS engines do **NOT  allow to use sync-https request**.
(Almost all API are implemented as callback-style, promise-style, or async-await style. 
sync api obsolated or not recommended.)

To support INLINE SVG means that we have to down-load svg from `kroki.io`, and insert it into `html` on parsing markdown syntax.
But, `markdown-it` plug-in **MUST** be implemented sync style..... [see here](https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#i-need-async-rule-how-to-do-it)

Is there fine method to fetch svg from kroki with sync ?
I have no idea...... sory....

**Comment by ezzle** [comment]
Help requested from Kroki team.

https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/Relative.20link.3A.20relative.20to.20site.20base.20instead.20of.20kroki.20server/near/419843489

**Comment by ggrossetie** [comment]
As far as I understand, this is a `markdown-it` limitation. You can use `XMLHttpRequest` to download the SVG from Kroki synchronously. `markdown-it` runs at build time (i.e., using Node.js or a headless browser) or at rendering time (client side) using the browser?
If it runs at build time, I guess it's fine to get content synchronously.

As a workaround, you could try output the SVG using an `<img>` tag. I'm not sure if links will resolve relative to the origin or relative to the target... But it's worth a try.

Another workaround, would be to prefix relative paths by the site base URL but your plugin probably doesn't know the base URL.

**Comment by kazumatu981** [comment]
@ggrossetie 
Thank you for your effort.
You are right ! 
As you said, the synchronously problem  is `markdown-it` limitation.
And as you said, to avoid the problem I can use `XMLHttpRequest`.

But I don't wanted to use the mehod by two reason.

First  of all, `XMLHttpRequest` is non-native method on `nodejs` environment.
If  we want to use this method, We have to use a third party library like [this](https://www.npmjs.com/package/xmlhttprequest).
I wanted to implement this library to be light-weight as possible.
(see `package.json`).

Secondary, basic concept of this libary is to create link urls for `krokii` and to embed them to html,
**NOT** to bring the image data over network and embed them.

## Conclusion

I'll consider for API, to be able to render yourself, like this.
```javascript
md.use(require('@kazumatu981/markdown-it-kroki'), {
        entrypoint: "https://kroki.io",
        render: imageRender
});
function imageRender(krokiUrl, someKindAttribute) {
     // build htmlFragment.... like INLINE SVG
    return htmlFragment;
}
```

How do you thik ??

**Comment by ggrossetie** [comment]
> I'll consider for API, to be able to render yourself, like this.

I think it's an excellent idea to give users the choice to implement another strategy in order to integrate their diagrams into the HTML page 👍🏻

**Comment by ezzle** [comment]
Thank you for the support.

Given the choice globally as well as per diagram inside each md could be
optimal.

Best regards,

Tshitshi

**Comment by kazumatu981** [comment]
Thanks all, I'll implement this interface. Just moment please....

**Comment by kazumatu981** [comment]
Hi all.

I've implemented.
Read [my memo](https://github.com/kazumatu981/markdown-it-kroki/blob/main/memo/howToWriteRender.md) and please enjoy.

**Comment by ezzle** [comment]
Hi.
Thank you very much. Unfortunately I don't see how to use it in my case.

@Guillaume Grossetie  could you help please?

Best regards,

Ts
