### ISSUE TITLE
D2 support

### ISSUE THREAD

**Issue by ezzle** [kazumatu981/markdown-it-kroki#8]
Please,

add "d2" support.

**Comment by ezzle** [comment]
Thank you very much for the support.

V1.2.3 not yet released ?

Best regards

Tshitshi

**Comment by kazumatu981** [comment]
?????

I have been released.
Please check [it](https://www.npmjs.com/package/@kazumatu981/markdown-it-kroki)

**Comment by ezzle** [comment]
https://github.com/kazumatu981/markdown-it-kroki

new version not yet documented.

Thanks.

Best regards

Tshitshi
